"""empty message

Revision ID: a71f2412f24a
Revises: 
Create Date: 2018-06-02 17:11:00.459090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a71f2412f24a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'type')
    # ### end Alembic commands ###


def upgrade_my_dom():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('email', table_name='users')
    op.drop_index('name', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade_my_dom():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_index('name', 'users', ['name'], unique=True)
    op.create_index('email', 'users', ['email'], unique=True)
    op.drop_table('error')
    # ### end Alembic commands ###

