"""empty message

Revision ID: c162d9374466
Revises: a71f2412f24a
Create Date: 2018-06-02 18:28:28.234244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c162d9374466'
down_revision = 'a71f2412f24a'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_my_dom():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('update_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade_my_dom():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'update_time')
    # ### end Alembic commands ###

